### ISSUE TITLE
Create a SDK to allow developers to start testing and create things without the need a personal cube

### ISSUE THREAD

**Issue by Vincent14** [siteswapjuggler/meuhcube#2]
I would create a backlog to list the ideas that could be useful for the project' SDK. Feel free to contribute :)

Two options
- Use an Arduino simulator to run the sketch on PC and develop the corresponding LED matrix to display outputs
- Rewrite a serial listener copying the messages' unpacker in the Arduino sketch, then develop the corresponding LED matrix to display outputs

**Comment by siteswapjuggler** [comment]
The developpement of an SDK would be usefull for a commercial or a large scale product. Even if it would be even manageable to rightfully simulate the arduino and the electronical attached to it.

Two simulation have been started so far, the max/msp patch wich could animate a 3D matrix of 343 boolean value and translate it into a compatible serial message to the cube. And the processing librairy which could be easily continuated to simulate the cube on screen and/or send the commands to the real cube.
