### ISSUE TITLE
Move USB clients in others git repositories

### ISSUE THREAD

**Issue by Vincent14** [siteswapjuggler/meuhcube#4]
It could be interesting to split git repositories by projects. This repo could store anything needed to have a functional LED cube (bom, hardware parts, firmware). I added the Python library to the main readme in one of my pull requests, we could list all clients there and let people contribute to them. It's only project management, but give more clarity in my opinion.

Example:

  * move software/max-msp folder to another repository
  * let software/processing simulator, move remote example to another repository

**Comment by siteswapjuggler** [comment]
The repositories represent a small scale hobbyist project no need to make it over complicated. The examples provided are simple and light weight. I intend to let them is this repository.
